library Tconfig requires TInitCustomTeams
function config_old takes nothing returns nothing
    call SetMapName("TRIGSTR_095")
    call SetMapDescription("TRIGSTR_096")
    call SetPlayers($C) // $C = 12
    call SetTeams($C) // $C = 12
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    call DefineStartLocation(0,28352.,3648.)
    call DefineStartLocation(1,28352.,3648.)
    call DefineStartLocation(2,28352.,3648.)
    call DefineStartLocation(3,28352.,3648.)
    call DefineStartLocation(4,28352.,3648.)
    call DefineStartLocation(5,28352.,3648.)
    call DefineStartLocation(6,28352.,3648.)
    call DefineStartLocation(7,28352.,3648.)
    call DefineStartLocation(8,-3392.,3136.)
    call DefineStartLocation(9,4480.,1856.)
    call DefineStartLocation($A,576.,512.) // $A = 10
    call DefineStartLocation($B,-3328.,2368.) // $B = 11
    call SetPlayerStartLocation(Player(0),0)
    call ForcePlayerStartLocation(Player(0),0)
    call SetPlayerColor(Player(0),ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(0),false)
    call SetPlayerController(Player(0),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(1),1)
    call ForcePlayerStartLocation(Player(1),1)
    call SetPlayerColor(Player(1),ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(1),false)
    call SetPlayerController(Player(1),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(2),2)
    call ForcePlayerStartLocation(Player(2),2)
    call SetPlayerColor(Player(2),ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(2),false)
    call SetPlayerController(Player(2),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(3),3)
    call ForcePlayerStartLocation(Player(3),3)
    call SetPlayerColor(Player(3),ConvertPlayerColor(3))
    call SetPlayerRacePreference(Player(3),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(3),false)
    call SetPlayerController(Player(3),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(4),4)
    call ForcePlayerStartLocation(Player(4),4)
    call SetPlayerColor(Player(4),ConvertPlayerColor(4))
    call SetPlayerRacePreference(Player(4),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(4),false)
    call SetPlayerController(Player(4),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(5),5)
    call ForcePlayerStartLocation(Player(5),5)
    call SetPlayerColor(Player(5),ConvertPlayerColor(5))
    call SetPlayerRacePreference(Player(5),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(5),false)
    call SetPlayerController(Player(5),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(6),6)
    call ForcePlayerStartLocation(Player(6),6)
    call SetPlayerColor(Player(6),ConvertPlayerColor(6))
    call SetPlayerRacePreference(Player(6),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(6),false)
    call SetPlayerController(Player(6),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(7),7)
    call ForcePlayerStartLocation(Player(7),7)
    call SetPlayerColor(Player(7),ConvertPlayerColor(7))
    call SetPlayerRacePreference(Player(7),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(7),false)
    call SetPlayerController(Player(7),MAP_CONTROL_USER)
    call SetPlayerStartLocation(Player(8),8)
    call ForcePlayerStartLocation(Player(8),8)
    call SetPlayerColor(Player(8),ConvertPlayerColor(8))
    call SetPlayerRacePreference(Player(8),RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(8),false)
    call SetPlayerController(Player(8),MAP_CONTROL_COMPUTER)
    call SetPlayerStartLocation(Player(9),9)
    call ForcePlayerStartLocation(Player(9),9)
    call SetPlayerColor(Player(9),ConvertPlayerColor(9))
    call SetPlayerRacePreference(Player(9),RACE_PREF_HUMAN)
    call SetPlayerRaceSelectable(Player(9),false)
    call SetPlayerController(Player(9),MAP_CONTROL_COMPUTER)
    call SetPlayerStartLocation(Player($A),$A) // $A = 10
    call ForcePlayerStartLocation(Player($A),$A) // $A = 10
    call SetPlayerColor(Player($A),ConvertPlayerColor($A)) // $A = 10
    call SetPlayerRacePreference(Player($A),RACE_PREF_HUMAN) // $A = 10
    call SetPlayerRaceSelectable(Player($A),false) // $A = 10
    call SetPlayerController(Player($A),MAP_CONTROL_COMPUTER) // $A = 10
    call SetPlayerStartLocation(Player($B),$B) // $B = 11
    call ForcePlayerStartLocation(Player($B),$B) // $B = 11
    call SetPlayerColor(Player($B),ConvertPlayerColor($B)) // $B = 11
    call SetPlayerRacePreference(Player($B),RACE_PREF_UNDEAD) // $B = 11
    call SetPlayerRaceSelectable(Player($B),false) // $B = 11
    call SetPlayerController(Player($B),MAP_CONTROL_COMPUTER) // $B = 11
    call InitCustomTeams_old()
    call SetStartLocPrioCount(0,7)
    call SetStartLocPrio(0,0,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,1,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,2,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,3,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,4,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(1,7)
    call SetStartLocPrio(1,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,1,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,2,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,3,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,4,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(2,7)
    call SetStartLocPrio(2,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,2,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,3,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,4,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(3,7)
    call SetStartLocPrio(3,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,2,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,3,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,4,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(3,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(4,7)
    call SetStartLocPrio(4,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,2,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,3,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,4,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(5,7)
    call SetStartLocPrio(5,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,2,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,3,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,4,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,5,6,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(6,7)
    call SetStartLocPrio(6,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,2,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,3,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,4,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,5,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6,6,7,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrioCount(7,7)
    call SetStartLocPrio(7,0,0,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,1,1,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,2,2,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,3,3,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,4,4,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,5,5,MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(7,6,6,MAP_LOC_PRIO_HIGH)
endfunction

function InitTrig_config takes nothing returns nothing
endfunction

endlibrary
