"""Read-only guards for existing G/H save-code compatibility and append-only items.

python tools/check_save_compat.py --map MAP.w3x
The contract is established from the user-tested stage S, never regenerated by builds.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re

from source_checks import ROOT, sources, literal_int, fingerprint, object_ids
from jtok import functions, strip_comments
import savecode

CONTRACT = ROOT / 'tools/contracts/save-compatibility.json'
FIXTURES = ROOT / 'tools/tests/fixtures/savecodes.json'


def assignments(texts, array, repeated=False):
    result, errors = {}, []
    pattern = r'\bset\s+' + re.escape(array) + r"\[([^]]+)\]\s*=\s*'([^']{4})'"
    for module, text in texts.items():
        for index, rawcode in re.findall(pattern, strip_comments(text)):
            number = literal_int(index)
            if number is None:
                errors.append(f'{module}: cannot statically resolve {array}[{index}]'); continue
            if repeated:
                result.setdefault(str(number), []).append(rawcode)
                continue
            if str(number) in result:
                errors.append(f'{array}[{number}]: duplicate assignment')
            result[str(number)] = rawcode
    return result, errors


def snapshot(map_path):
    _, texts = sources()
    items, errors = assignments(texts, 'udg_ItemIdTable')
    jobs, extra = assignments(texts, 'udg_JobUnitType'); errors += extra
    flags, extra = assignments(texts, 'udg_SaveFlagUnitID', repeated=True); errors += extra
    counts = re.findall(r'\bset\s+udg_SaveFlagCount\s*=\s*([^\r\n]+)', strip_comments('\n'.join(texts.values())))
    flag_count = literal_int(counts[0].strip()) if len(counts) == 1 else None
    if flag_count is None:
        errors.append('udg_SaveFlagCount must have one statically resolved initialization')
    serializers = {}
    for module in ['Save', 'Cmd', 'Code']:
        for name, body in functions(texts[module]).items():
            if name.startswith(('Save_', 'Code_', 'Trig_Cmd_Load_Code_')):
                serializers[name] = fingerprint(body)
    table = savecode.load_items(str(ROOT / 'src/itemtable.txt'))
    ids, fields, extra = object_ids(map_path); errors += extra
    for index, rawcode in items.items():
        if rawcode not in ids.get('item', set()):
            errors.append(f'item table {index}: object {rawcode} missing from map')
    for index, rawcode in jobs.items():
        if rawcode not in ids.get('unit', set()):
            errors.append(f'job table {index}: unit {rawcode} missing from map')
    return {'items': items, 'jobs': jobs, 'armory_flags': flags, 'serializers': serializers,
            'save_flag_count': flag_count,
            'charged': {str(k): v['charged'] for k, v in table.items()},
            'item_bases': {raw: fields.get(raw, {}).get('_base') for raw in items.values()},
            'item_classes': {raw: fields.get(raw, {}).get('icla') for raw in items.values()}}, errors


def compare(current, contract):
    errors = []
    items = current['items']
    numeric = sorted(int(k) for k in items)
    if not numeric or numeric != list(range(1, max(numeric) + 1)):
        errors.append('save item indexes must be contiguous from 1')
    if numeric and max(numeric) > 500:
        errors.append('save item index exceeds 500 and overlaps reserved armory flags 501..540')
    if numeric and current['save_flag_count'] != max(numeric):
        errors.append('udg_SaveFlagCount must equal the highest contiguous item index')
    for raw, count in Counter(items.values()).items():
        if count > 1:
            errors.append(f'duplicate save item rawcode {raw}')
    for key in ['items', 'charged', 'item_classes', 'item_bases', 'armory_flags', 'serializers']:
        for index, original in contract[key].items():
            if current[key].get(index) != original:
                errors.append(f'{key}/{index}: existing save contract changed or removed')
    if current['jobs'] != contract['jobs']:
        errors.append('job order/count changed: a new save format and preserved legacy readers are required')
    for key in items:
        if key not in current['charged']:
            errors.append(f'item {key}: refresh src/itemtable.txt with -dumpitems to record its charge classification')
    return errors


def fixtures_check(table, path=FIXTURES):
    errors = []
    charged = lambda i: table[i]['charged']
    for case in json.loads(path.read_text(encoding='utf-8'))['cases']:
        try:
            actual, _ = savecode.decode(case['code'], charged)
            expected = case['expected']
            if savecode.encode(case['input'], charged, case.get('armory', '')) != case['code']:
                errors.append(f"save fixture {case['name']}: encoded bytes changed")
            # JSON stores inventory tuples as lists.
            actual = json.loads(json.dumps(actual))
            if actual != expected:
                errors.append(f"save fixture {case['name']}: decoded fields changed")
            if savecode.code_name_hash(case['code'])[1] != savecode.name_hash(case['player']):
                errors.append(f"save fixture {case['name']}: account hash mismatch")
            moved = savecode.rename(case['code'], 'CompatibilityCheck#1234')
            renamed, _ = savecode.decode(moved, charged)
            renamed = json.loads(json.dumps(renamed))
            if {k: v for k, v in renamed.items() if k != 'name_hash'} != {k: v for k, v in actual.items() if k != 'name_hash'}:
                errors.append(f"save fixture {case['name']}: rename changed payload")
            if '(' in case['code']:
                old_armory = case['code'].split('(', 1)[1].rstrip(')')
                new_armory = moved.split('(', 1)[1].rstrip(')')
                if new_armory != savecode.rename_armory(case['code'][1:4], old_armory, moved[1:4]):
                    errors.append(f"save fixture {case['name']}: armory link/checksum changed incorrectly")
        except (savecode.CodeError, KeyError) as exc:
            errors.append(f"save fixture {case['name']}: {exc}")
    return errors


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--map', type=Path, required=True)
    p.add_argument('--record-tested-baseline', action='store_true')
    a = p.parse_args()
    current, errors = snapshot(a.map)
    if a.record_tested_baseline:
        if CONTRACT.exists():
            p.error('contract exists; changing it requires an explicit compatibility review')
        if errors:
            raise SystemExit('\n'.join(errors))
        current['baseline'] = a.map.name
        current['sha256'] = hashlib.sha256(a.map.read_bytes()).hexdigest()
        CONTRACT.parent.mkdir(parents=True, exist_ok=True)
        CONTRACT.write_text(json.dumps(current, indent=2) + '\n', encoding='utf-8')
        print('Recorded tested save tables and serializer fingerprints.')
        return 0
    errors += compare(current, json.loads(CONTRACT.read_text(encoding='utf-8')))
    table = savecode.load_items(str(ROOT / 'src/itemtable.txt'))
    for index, rawcode in current['items'].items():
        if int(index) not in table or table[int(index)]['id'] != rawcode:
            errors.append(f'itemtable.txt index {index} disagrees with udg_ItemIdTable')
    errors += fixtures_check(table)
    for error in errors[:40]:
        print('FAIL ' + error)
    print(f"{'FAIL' if errors else 'PASS'} save compatibility: {len(current['items'])} items, {len(current['jobs'])} jobs, preserved readers/writer/armory flags and fixed G/H fixtures")
    return int(bool(errors))


if __name__ == '__main__':
    raise SystemExit(main())
