"""Refresh the declared library dependency index from src/ (not a call graph)."""
import re
from pathlib import Path

from gen_docs import load, ROOT
from jtok import strip_comments


def main():
    modules, _ = load(str(Path(ROOT) / 'src'))
    rows = []
    for name, module in modules.items():
        text = strip_comments(module['text'])
        declaration = re.search(r'^\s*library\s+(\w+)([^\n]*)', text, re.M)
        if not declaration:
            raise ValueError(f'{name}: no library declaration')
        library, suffix = declaration.groups()
        dependencies = re.search(r'\b(?:requires|needs|uses)\s+(.+)', suffix)
        required, optional = [], []
        for dependency in (dependencies.group(1).split(',') if dependencies else []):
            words = dependency.strip().split()
            (optional if words[0] == 'optional' else required).append(words[-1])
        path = '../src/triggers/' + module['folder'] + '/' + name + '.j'
        rows.append(f'| `{library}` | [{name}](<{path}>) | ' +
                    ', '.join(f'`{x}`' for x in required) + ' | ' +
                    ', '.join(f'`{x}`' for x in optional) + ' |')
    output = Path(ROOT) / 'docs' / 'LIBRARY_DEPENDENCIES.md'
    output.write_text('# Declared library dependencies\n\n'
                      'Generated by `python tools/gen_dependencies.py` from current source.\n'
                      f'Includes {len(rows)} editor libraries, including disabled modules.\n'
                      'Requires clauses determine library order; optional dependencies are conditional.\n'
                      'This is not a complete function/ExecuteFunc/startup dependency graph.\n'
                      'Use check_quests/check_map and disable_check for additional checks.\n\n'
                      '| Library | Module | Required | Optional |\n'
                      '|---|---|---|---|\n' + '\n'.join(rows) + '\n', encoding='utf-8')
    print(f'Wrote {len(rows)} library declarations to {output}')


if __name__ == '__main__':
    main()
