"""Write a readable reference of the map's custom objects (Object Editor data).

    python tools/objects.py MAP.w3x [DOCS_DIR]

Writes DOCS_DIR/objects/*.md and *.csv (units, items, abilities, buffs, upgrades, destructables,
doodads):
  id, the object it was copied from, name, a few key values, and which code modules use it.
"Not used by code" means no trigger mentions the id; the object may still be placed on the map,
sold in a shop or given by another object, so check before deleting.
Also writes src/items-guess.json (save index -> item id, name, charged?) for tools/savecode.py.
"""
import collections, csv, json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from mpq import MPQ
from objdata import read_objects, fields

ROOT = os.path.dirname(HERE)
KINDS = [  # file ext, title, name field, key fields
    ('w3u', 'Units', 'unam', [('ulev', 'level'), ('uhpm', 'HP'), ('umpm', 'mana'), ('udef', 'armor'), ('ua1b', 'damage base'), ('upri', 'priority')]),
    ('w3t', 'Items', 'unam', [('icla', 'class'), ('ilev', 'level'), ('igol', 'gold'), ('iuse', 'charges'), ('iabi', 'abilities')]),
    ('w3a', 'Abilities', 'anam', [('aher', 'hero ability'), ('alev', 'levels'), ('arac', 'race')]),
    ('w3h', 'Buffs', 'fnam', [('ftip', 'tooltip')]),
    ('w3q', 'Upgrades', 'gnam', [('glvl', 'levels')]),
    ('w3b', 'Destructables', 'bnam', []),
    ('w3d', 'Doodads', 'dnam', []),
]

def wts_strings(m):
    raw = m.read('war3map.wts') or b''
    text = raw.decode('utf-8-sig', 'replace')
    return {int(k): v.replace('\r\n', ' ').strip() for k, v in re.findall(r'STRING (\d+)\r?\n(?://[^\n]*\n)?\{\r?\n(.*?)\r?\n\}', text, re.S)}

def resolve(v, strings):
    if isinstance(v, str):
        mm = re.fullmatch(r'TRIGSTR_(\d+)', v)
        if mm:
            return strings.get(int(mm.group(1)), v)
        return re.sub(r'\|c[0-9A-Fa-f]{8}|\|r', '', v)
    return v

def code_refs():
    """rawcode -> set of modules whose code mentions it; and names from the code's comments."""
    refs, names = collections.defaultdict(set), {}
    for root, _, files in os.walk(os.path.join(ROOT, 'src', 'triggers')):
        for f in files:
            text = open(os.path.join(root, f), encoding='utf-8').read()
            mod = f[:-2]
            for rc in set(re.findall(r"'([A-Za-z0-9]{4})'", re.sub(r'//[^\n]*', '', text))):
                refs[rc].add(mod)
            for rc, kind, nm in re.findall(r"'([A-Za-z0-9]{4})': (?:editor label |)(\w+)? ?\"([^\"]+)\"", text):
                names.setdefault(rc, nm)
    return refs, names

def main(map_path, docs):
    m = MPQ(map_path)
    strings = wts_strings(m)
    refs, code_names = code_refs()
    out_dir = os.path.join(docs, 'objects')
    os.makedirs(out_dir, exist_ok=True)
    index = ['# Object reference', '', 'Generated by `tools/objects.py` from the map\'s Object Editor data.',
             'One page per object type: custom objects (new ids) and changed standard objects.', '']
    all_items = {}
    for ext, title, name_field, keys in KINDS:
        objs = collections.OrderedDict()
        for fname in ('war3map.' + ext, 'war3mapSkin.' + ext):
            data = m.read(fname)
            if not data:
                continue
            t = read_objects(data, ext)
            for table in ('custom', 'original'):
                for o in t[table]:
                    oid = o['id'] or o['base']
                    rec = objs.setdefault(oid, dict(id=oid, base=o['base'], custom=table == 'custom', f={}))
                    rec['f'].update(fields(o))
        rows = []
        for oid, rec in objs.items():
            f = rec['f']
            name = resolve(f.get(name_field) or f.get((name_field, 1)) or '', strings) or code_names.get(oid, '')
            if ext == 'w3t':
                all_items[oid] = dict(name=name, cls=f.get('icla'), base=rec['base'])
            used = sorted(refs.get(oid, ()))
            rows.append([oid, rec['base'] if rec['custom'] else '(standard, changed)', name] +
                        [str(resolve(f.get(k, f.get((k, 1), '')), strings))[:60] for k, _ in keys] +
                        [', '.join(used[:6]) + (' +%d' % (len(used) - 6) if len(used) > 6 else '') if used else 'not used by code'])
        head = ['id', 'copied from', 'name'] + [lbl for _, lbl in keys] + ['used by (modules)']
        with open(os.path.join(out_dir, title.upper() + '.csv'), 'w', newline='', encoding='utf-8') as fh:
            csv.writer(fh).writerows([head] + rows)
        md = ['# %s' % title, '', 'Generated by `tools/objects.py`. %d objects (%d custom). Same data as `%s.csv`.' % (
            len(rows), sum(1 for r in objs.values() if r['custom']), title.upper()), '',
              '| ' + ' | '.join(head) + ' |', '|' + '---|' * len(head)]
        md += ['| ' + ' | '.join(c.replace('|', '/') for c in r) + ' |' for r in rows]
        open(os.path.join(out_dir, title.upper() + '.md'), 'w', encoding='utf-8').write('\n'.join(md) + '\n')
        unused = sum(1 for r in rows if r[-1] == 'not used by code')
        index.append('- [%s](objects/%s.md): %d objects, %d not mentioned by any code' % (title, title.upper(), len(rows), unused))
    open(os.path.join(docs, 'OBJECTS.md'), 'w', encoding='utf-8').write('\n'.join(index) + '\n')
    # save index -> item (from the Armory table) for tools/savecode.py
    armory = open(os.path.join(ROOT, 'src', 'triggers', '05 Items crafting and shops', 'Armory.j'), encoding='utf-8').read()
    guess = {}
    for k, rc in re.findall(r"set udg_ItemIdTable\[(\$?\w+)\]='(\w{4})'", armory):
        i = int(k[1:], 16) if k.startswith('$') else int(k)
        it = all_items.get(rc, {})
        guess[i] = dict(id=rc, name=it.get('name') or code_names.get(rc, rc), charged=it.get('cls') == 'Charged',
                        sure=it.get('cls') is not None)
    json.dump(guess, open(os.path.join(ROOT, 'src', 'items-guess.json'), 'w', encoding='utf-8'), indent=0)
    print('\n'.join(index[5:]))
    print('items-guess.json: %d save indexes (%d with a known item class)' % (len(guess), sum(1 for g in guess.values() if g['sure'])))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'docs'))
