"""Write docs/QUESTS.md: how the quests and story chapters switch each other on.

    python tools/quest_map.py

Quests in this map are chains of triggers: finishing one step enables (or runs) the triggers of the
next. This reads every module, finds which TRIGGER's code enables/runs which other trigger, and
writes per quest module:
  * the quest-log entry it creates (title and text, if any),
  * what turns its triggers on (which modules), and what it turns on.
It also writes docs/quest-graph.mmd, a Mermaid graph of the module links (paste it into
https://mermaid.live or view it on GitHub).
Covers the folders "06 Quests and story" and the bosses; follow links outside them in TRIGGER_INDEX.md.
"""
import collections, json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from jtok import strip_comments

ROOT = os.path.dirname(HERE)
FUNC = re.compile(r'^\s*(?:constant\s+)?function\s+(\w+)\s+takes.*?^\s*endfunction', re.M | re.S)
LIT = r'"(?:\\.|[^"\\])*"'

def load():
    entries = json.load(open(os.path.join(ROOT, 'src', 'trigger-list.json'), encoding='utf-8'))
    mods = collections.OrderedDict()
    for e in entries:
        if e.get('library'):
            p = os.path.join(ROOT, 'src', 'triggers', e['folder'], e['name'] + '.j')
            mods[e['name']] = dict(folder=e['folder'], text=open(p, encoding='utf-8').read().replace('\r\n', '\n'))
    return mods

def main():
    mods = load()
    trig_module = {}
    for n, m in mods.items():
        for t in re.findall(r'^\s*function\s+Register_(\w+)\s+takes', m['text'], re.M):
            trig_module[t] = n
    # function -> trigger whose code it is (Trig_<Trigger>_...)
    by_len = sorted(trig_module, key=len, reverse=True)
    def owner(fn):
        if fn.startswith('Trig_'):
            for t in by_len:
                if fn.startswith('Trig_' + t + '_'):
                    return t
        return None
    links = collections.defaultdict(lambda: collections.defaultdict(set))   # src module -> dst module -> {(src trig, verb, dst trig)}
    for n, m in mods.items():
        for fm in FUNC.finditer(strip_comments(m['text'])):
            if fm.group(1).startswith('Register_'):
                continue
            src_t = owner(fm.group(1)) or fm.group(1)
            for verb, pat in (('enables', r'EnableTrigger'), ('runs', r'(?:Conditional)?TriggerExecute'), ('disables', r'DisableTrigger')):
                for dst in re.findall(r'\b(?:%s)\s*\(\s*gg_trg_(\w+)\s*\)' % pat, fm.group(0)):
                    if dst in trig_module and trig_module[dst] != n:
                        links[n][trig_module[dst]].add((src_t, verb, dst))
    story = [n for n, m in mods.items() if m['folder'].startswith('06') or n.startswith('Boss_')]
    incoming = collections.defaultdict(set)
    for s, d in links.items():
        for t in d:
            incoming[t].add(s)
    def quest_entries(text):
        out = []
        for mm in re.finditer(r'CreateQuestBJ\s*\(\s*(\w+)\s*,\s*(.*?)\s*,\s*(%s)\s*,' % LIT, text):
            title = ' '.join(re.findall(LIT, mm.group(2))).replace('"', '')
            title = re.sub(r'\|c[0-9a-fA-F]{8}|\|r', '', title)
            out.append((title.strip() or '(title from a variable)', mm.group(1).replace('bj_QUESTTYPE_', '').lower(),
                        re.sub(r'\|c[0-9a-fA-F]{8}|\|r|\\n|\\r', ' ', mm.group(3)[1:-1])[:160]))
        return out
    lines = ['# Quests and story: what turns on what', '',
             'Generated by `tools/quest_map.py`. Quests are chains of triggers: a step finishes and enables (or runs)',
             'the triggers of the next step. For each quest/story module: the quest-log entry it creates, which modules',
             'switch its triggers, and which modules it switches. "A → B" means code in A enables, runs or disables a trigger of B.',
             '`docs/quest-graph.mmd` draws the same links as a graph. Per-trigger detail: `TRIGGER_INDEX.md`.', '',
             '## Where chains start', '',
             'Modules nothing else switches on (they start from map start, a region, an item or a chat command):', '']
    starts = [n for n in story if not incoming[n] and links.get(n)]
    lines.append(', '.join('`%s`' % s for s in starts) or '(none)')
    lines += ['', '## Modules', '']
    for n in story:
        qe = quest_entries(mods[n]['text'])
        ins = sorted(incoming[n])
        outs = links.get(n, {})
        if not (qe or ins or outs):
            continue
        lines.append('### %s' % n)
        for title, kind, text in qe[:3]:
            lines.append('- Quest log: **%s** (%s) - %s' % (title, kind, text))
        if ins:
            lines.append('- Linked from (enables, runs or disables its triggers): ' + ', '.join('`%s`' % i for i in ins))
        for d, items in sorted(outs.items()):
            ex = sorted(items)[:3]
            lines.append('- → `%s`: %s%s' % (d, '; '.join('%s %s %s' % e for e in ex), ' …' if len(items) > 3 else ''))
        lines.append('')
    open(os.path.join(ROOT, 'docs', 'QUESTS.md'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    g = ['flowchart LR']
    ids = {}
    def nid(x):
        return ids.setdefault(x, 'm%d' % len(ids))
    for s in story:
        for d in sorted(links.get(s, {})):
            if d in story:
                g.append('  %s[%s] --> %s[%s]' % (nid(s), s, nid(d), d))
    open(os.path.join(ROOT, 'docs', 'quest-graph.mmd'), 'w', encoding='utf-8').write('\n'.join(g) + '\n')
    print('QUESTS.md: %d modules, %d chain starts, %d graph edges' % (len(story), len(starts), len(g) - 1))

if __name__ == '__main__':
    main()
