flowchart LR
  m0[Boss_Agrias] --> m1[Boss_Lilith]
  m2[Boss_Belias] --> m3[Boss_Demesne]
  m2[Boss_Belias] --> m4[Boss_Hashmalum]
  m2[Boss_Belias] --> m5[Boss_Mateus]
  m2[Boss_Belias] --> m6[Quest_WorldLiberation]
  m7[Boss_Chaos] --> m8[Elemental]
  m7[Boss_Chaos] --> m6[Quest_WorldLiberation]
  m9[Boss_DarkRanger] --> m10[Quest_FallenRanger]
  m11[Boss_Echele] --> m12[IceAge]
  m11[Boss_Echele] --> m13[TrueIceAge]
  m14[Boss_Exodus] --> m6[Quest_WorldLiberation]
  m15[Boss_Famfrit] --> m6[Quest_WorldLiberation]
  m16[Boss_Gafgarion] --> m17[Boss_Zalera]
  m4[Boss_Hashmalum] --> m2[Boss_Belias]
  m4[Boss_Hashmalum] --> m18[Dwarves]
  m4[Boss_Hashmalum] --> m19[Gafgarion]
  m4[Boss_Hashmalum] --> m6[Quest_WorldLiberation]
  m1[Boss_Lilith] --> m20[Alma]
  m5[Boss_Mateus] --> m3[Boss_Demesne]
  m5[Boss_Mateus] --> m6[Quest_WorldLiberation]
  m21[Boss_Shemhazai] --> m6[Quest_WorldLiberation]
  m22[Boss_Ultima] --> m6[Quest_WorldLiberation]
  m23[Boss_Yukale] --> m9[Boss_DarkRanger]
  m17[Boss_Zalera] --> m16[Boss_Gafgarion]
  m17[Boss_Zalera] --> m24[Celeborn]
  m17[Boss_Zalera] --> m25[DeathSeeker]
  m17[Boss_Zalera] --> m26[KalmSiege1]
  m17[Boss_Zalera] --> m6[Quest_WorldLiberation]
  m27[Ending] --> m28[Bernkastel]
  m27[Ending] --> m29[Mid]
  m27[Ending] --> m30[Quest_SaveTimmy]
  m31[Quest_AnnoyingMonster] --> m32[AnnoyingMonster]
  m33[Quest_Arachnophobia] --> m34[QuestCount]
  m33[Quest_Arachnophobia] --> m35[Quest_HarpyHunt]
  m36[Quest_Arcanium] --> m37[Ziegfried]
  m38[Quest_Beastslayer] --> m34[QuestCount]
  m39[Quest_BlazingDemon] --> m40[BlazingDemon]
  m39[Quest_BlazingDemon] --> m41[ScorchedEarth]
  m42[Quest_Brothers] --> m43[Brothers]
  m42[Quest_Brothers] --> m34[QuestCount]
  m44[Quest_Caravan] --> m34[QuestCount]
  m45[Quest_DarkKnight] --> m16[Boss_Gafgarion]
  m45[Quest_DarkKnight] --> m8[Elemental]
  m46[Quest_DeliverLetter] --> m34[QuestCount]
  m47[Quest_DivineOrder] --> m48[PhantomDiary]
  m47[Quest_DivineOrder] --> m37[Ziegfried]
  m49[Quest_DwarfDisappearance] --> m50[Valigarmanda]
  m51[Quest_EidolonChallenge] --> m43[Brothers]
  m52[Quest_EyeOfJenova] --> m53[Quest_NightElves]
  m10[Quest_FallenRanger] --> m23[Boss_Yukale]
  m54[Quest_FireGolem] --> m55[MithrilGolem]
  m54[Quest_FireGolem] --> m34[QuestCount]
  m56[Quest_Fountain] --> m57[DefiledFountain]
  m58[Quest_GodDragon] --> m59[Zodiark]
  m60[Quest_GreedIsGood] --> m61[GreedIsGood]
  m60[Quest_GreedIsGood] --> m62[PortalStone]
  m35[Quest_HarpyHunt] --> m34[QuestCount]
  m63[Quest_HolyKnight] --> m0[Boss_Agrias]
  m64[Quest_Illusions] --> m65[Dana]
  m66[Quest_ImperviousBeast] --> m67[Fafnir]
  m66[Quest_ImperviousBeast] --> m68[Siegfried]
  m66[Quest_ImperviousBeast] --> m37[Ziegfried]
  m69[Quest_KillElmdor] --> m34[QuestCount]
  m69[Quest_KillElmdor] --> m42[Quest_Brothers]
  m70[Quest_KillSetag] --> m34[QuestCount]
  m71[Quest_LadyNashj] --> m65[Dana]
  m72[Quest_LastRites] --> m73[Exodus]
  m74[Quest_LightOfJudgment] --> m75[Ultima]
  m76[Quest_LostMemories] --> m77[Shadow_Lifecycle]
  m78[Quest_Monstrum] --> m79[Monstrum]
  m80[Quest_NebraAngler] --> m81[Quest_KingOfSea]
  m53[Quest_NightElves] --> m82[ArenaResources]
  m53[Quest_NightElves] --> m83[BridgeBattle]
  m53[Quest_NightElves] --> m57[DefiledFountain]
  m53[Quest_NightElves] --> m84[HealingWaters]
  m53[Quest_NightElves] --> m85[Liniel]
  m53[Quest_NightElves] --> m86[MysteriousCurse]
  m53[Quest_NightElves] --> m87[NightElf]
  m53[Quest_NightElves] --> m88[Nimphrodel]
  m53[Quest_NightElves] --> m89[Npc]
  m53[Quest_NightElves] --> m34[QuestCount]
  m53[Quest_NightElves] --> m71[Quest_LadyNashj]
  m53[Quest_NightElves] --> m90[ShinrasPlan]
  m53[Quest_NightElves] --> m91[Talk]
  m92[Quest_NorthernGod] --> m93[Judgment]
  m94[Quest_OgreHunt] --> m34[QuestCount]
  m95[Quest_OmegaWeapon] --> m96[AlmightyShinra]
  m97[Quest_OreSupplies] --> m98[Loki]
  m99[Quest_PhantomDiary] --> m92[Quest_NorthernGod]
  m100[Quest_Phoenix] --> m34[QuestCount]
  m100[Quest_Phoenix] --> m54[Quest_FireGolem]
  m30[Quest_SaveTimmy] --> m101[NameDiary]
  m30[Quest_SaveTimmy] --> m89[Npc]
  m30[Quest_SaveTimmy] --> m44[Quest_Caravan]
  m102[Quest_ScorchedEarth] --> m103[IcyRealm]
  m102[Quest_ScorchedEarth] --> m104[McBurn]
  m102[Quest_ScorchedEarth] --> m41[ScorchedEarth]
  m105[Quest_SeekDestroy] --> m89[Npc]
  m106[Quest_Shimmerweed] --> m34[QuestCount]
  m107[Quest_SpiritOfWater] --> m108[Priscilla]
  m107[Quest_SpiritOfWater] --> m109[Tiara]
  m107[Quest_SpiritOfWater] --> m110[Vodyan]
  m111[Quest_StrongestEidolon] --> m112[Eden]
  m113[Quest_TargetPractice] --> m114[TargetPractice]
  m115[Quest_UltimaWeapon] --> m108[Priscilla]
  m115[Quest_UltimaWeapon] --> m95[Quest_OmegaWeapon]
  m116[Quest_WolfFangs] --> m34[QuestCount]
  m6[Quest_WorldLiberation] --> m90[ShinrasPlan]
  m117[Quest_YoungEngineer] --> m118[Quest_Crossbow]
  m117[Quest_YoungEngineer] --> m119[Quest_Engineer]
  m120[Quest_ZodiacAge] --> m103[IcyRealm]
  m120[Quest_ZodiacAge] --> m64[Quest_Illusions]
  m121[Zeromus] --> m122[Agrias]
  m121[Zeromus] --> m123[Frakir]
  m121[Zeromus] --> m6[Quest_WorldLiberation]
  m121[Zeromus] --> m90[ShinrasPlan]
  m124[Shadow_Hiring] --> m77[Shadow_Lifecycle]
  m124[Shadow_Hiring] --> m125[Shadow_Loyalty]
  m77[Shadow_Lifecycle] --> m76[Quest_LostMemories]
  m77[Shadow_Lifecycle] --> m124[Shadow_Hiring]
  m77[Shadow_Lifecycle] --> m125[Shadow_Loyalty]
  m125[Shadow_Loyalty] --> m124[Shadow_Hiring]
  m126[Makenroh] --> m127[DragonHunt]
  m128[Gilgamesh] --> m83[BridgeBattle]
  m129[Cid] --> m123[Frakir]
  m129[Cid] --> m130[GoblinChief]
  m129[Cid] --> m29[Mid]
  m129[Cid] --> m131[Monica]
  m129[Cid] --> m132[MysticalGlyph]
  m129[Cid] --> m133[Naisha]
  m129[Cid] --> m34[QuestCount]
  m129[Cid] --> m33[Quest_Arachnophobia]
  m129[Cid] --> m38[Quest_Beastslayer]
  m129[Cid] --> m44[Quest_Caravan]
  m129[Cid] --> m46[Quest_DeliverLetter]
  m129[Cid] --> m69[Quest_KillElmdor]
  m129[Cid] --> m70[Quest_KillSetag]
  m129[Cid] --> m106[Quest_Shimmerweed]
  m129[Cid] --> m77[Shadow_Lifecycle]
  m129[Cid] --> m134[Turks]
  m129[Cid] --> m135[Valera]
  m29[Mid] --> m129[Cid]
  m29[Mid] --> m123[Frakir]
  m29[Mid] --> m136[Giott]
  m29[Mid] --> m132[MysticalGlyph]
  m29[Mid] --> m133[Naisha]
  m29[Mid] --> m34[QuestCount]
  m29[Mid] --> m33[Quest_Arachnophobia]
  m29[Mid] --> m106[Quest_Shimmerweed]
  m29[Mid] --> m117[Quest_YoungEngineer]
  m29[Mid] --> m77[Shadow_Lifecycle]
  m29[Mid] --> m135[Valera]
  m137[AoMadoushi] --> m138[Quest_AoMadoushi]
  m91[Talk] --> m83[BridgeBattle]
  m91[Talk] --> m57[DefiledFountain]
  m91[Talk] --> m85[Liniel]
  m91[Talk] --> m86[MysteriousCurse]
  m91[Talk] --> m87[NightElf]
  m91[Talk] --> m71[Quest_LadyNashj]
  m91[Talk] --> m90[ShinrasPlan]
  m26[KalmSiege1] --> m139[KalmSiege]
  m26[KalmSiege1] --> m140[KalmSiege2]
  m26[KalmSiege1] --> m29[Mid]
  m26[KalmSiege1] --> m108[Priscilla]
  m26[KalmSiege1] --> m34[QuestCount]
  m140[KalmSiege2] --> m139[KalmSiege]
  m140[KalmSiege2] --> m141[KalmSiege3]
  m140[KalmSiege2] --> m34[QuestCount]
  m141[KalmSiege3] --> m139[KalmSiege]
  m141[KalmSiege3] --> m142[Meliadoul]
  m141[KalmSiege3] --> m34[QuestCount]
  m141[KalmSiege3] --> m6[Quest_WorldLiberation]
  m142[Meliadoul] --> m143[Quest_CorruptedOrcs]
  m144[OrcBase] --> m143[Quest_CorruptedOrcs]
  m144[OrcBase] --> m145[Shemhazai]
  m65[Dana] --> m146[DragonEgg]
  m65[Dana] --> m147[Epilogue]
  m65[Dana] --> m148[Famfrit]
  m65[Dana] --> m149[FlanHunt]
  m65[Dana] --> m89[Npc]
  m65[Dana] --> m64[Quest_Illusions]
  m65[Dana] --> m120[Quest_ZodiacAge]
  m65[Dana] --> m114[TargetPractice]
  m65[Dana] --> m150[Tentacles]
  m151[Montblanc] --> m58[Quest_GodDragon]
  m19[Gafgarion] --> m11[Boss_Echele]
  m12[IceAge] --> m11[Boss_Echele]
  m12[IceAge] --> m27[Ending]
  m12[IceAge] --> m19[Gafgarion]
  m13[TrueIceAge] --> m137[AoMadoushi]
  m13[TrueIceAge] --> m11[Boss_Echele]
  m13[TrueIceAge] --> m14[Boss_Exodus]
  m13[TrueIceAge] --> m15[Boss_Famfrit]
  m13[TrueIceAge] --> m5[Boss_Mateus]
  m13[TrueIceAge] --> m21[Boss_Shemhazai]
  m13[TrueIceAge] --> m129[Cid]
  m13[TrueIceAge] --> m65[Dana]
  m13[TrueIceAge] --> m18[Dwarves]
  m13[TrueIceAge] --> m8[Elemental]
  m13[TrueIceAge] --> m27[Ending]
  m13[TrueIceAge] --> m147[Epilogue]
  m13[TrueIceAge] --> m73[Exodus]
  m13[TrueIceAge] --> m148[Famfrit]
  m13[TrueIceAge] --> m84[HealingWaters]
  m13[TrueIceAge] --> m152[PriestX]
  m13[TrueIceAge] --> m108[Priscilla]
  m13[TrueIceAge] --> m34[QuestCount]
  m13[TrueIceAge] --> m64[Quest_Illusions]
  m13[TrueIceAge] --> m72[Quest_LastRites]
  m13[TrueIceAge] --> m145[Shemhazai]
  m13[TrueIceAge] --> m90[ShinrasPlan]
  m13[TrueIceAge] --> m91[Talk]
  m13[TrueIceAge] --> m134[Turks]
  m147[Epilogue] --> m82[ArenaResources]
  m147[Epilogue] --> m83[BridgeBattle]
  m147[Epilogue] --> m25[DeathSeeker]
  m147[Epilogue] --> m57[DefiledFountain]
  m147[Epilogue] --> m136[Giott]
  m147[Epilogue] --> m85[Liniel]
  m147[Epilogue] --> m29[Mid]
  m147[Epilogue] --> m131[Monica]
  m147[Epilogue] --> m86[MysteriousCurse]
  m147[Epilogue] --> m87[NightElf]
  m147[Epilogue] --> m88[Nimphrodel]
  m147[Epilogue] --> m34[QuestCount]
  m147[Epilogue] --> m38[Quest_Beastslayer]
  m147[Epilogue] --> m44[Quest_Caravan]
  m147[Epilogue] --> m46[Quest_DeliverLetter]
  m147[Epilogue] --> m69[Quest_KillElmdor]
  m147[Epilogue] --> m70[Quest_KillSetag]
  m147[Epilogue] --> m71[Quest_LadyNashj]
  m147[Epilogue] --> m90[ShinrasPlan]
  m147[Epilogue] --> m91[Talk]
  m114[TargetPractice] --> m153[Aisha]
  m114[TargetPractice] --> m113[Quest_TargetPractice]
  m84[HealingWaters] --> m34[QuestCount]
  m55[MithrilGolem] --> m154[GolemHeart]
  m55[MithrilGolem] --> m34[QuestCount]
  m55[MithrilGolem] --> m155[StrangeKey]
  m154[GolemHeart] --> m55[MithrilGolem]
  m156[HydraEgg] --> m89[Npc]
  m132[MysticalGlyph] --> m34[QuestCount]
  m132[MysticalGlyph] --> m157[Storm]
  m88[Nimphrodel] --> m158[CrystalBall]
  m88[Nimphrodel] --> m89[Npc]
  m86[MysteriousCurse] --> m89[Npc]
  m57[DefiledFountain] --> m56[Quest_Fountain]
  m131[Monica] --> m94[Quest_OgreHunt]
  m61[GreedIsGood] --> m62[PortalStone]
  m62[PortalStone] --> m60[Quest_GreedIsGood]
  m85[Liniel] --> m10[Quest_FallenRanger]
  m108[Priscilla] --> m107[Quest_SpiritOfWater]
  m108[Priscilla] --> m111[Quest_StrongestEidolon]
  m48[PhantomDiary] --> m99[Quest_PhantomDiary]
  m93[Judgment] --> m159[Boss_Odin]
  m160[LadyCurse] --> m34[QuestCount]
  m160[LadyCurse] --> m31[Quest_AnnoyingMonster]
  m82[ArenaResources] --> m161[ArenaExpansion]
  m162[DimensionalBoundary] --> m123[Frakir]
  m162[DimensionalBoundary] --> m163[GuideBook]
  m162[DimensionalBoundary] --> m90[ShinrasPlan]
  m162[DimensionalBoundary] --> m121[Zeromus]
  m163[GuideBook] --> m164[TropicalEssence]
  m165[FrogHead] --> m162[DimensionalBoundary]
  m87[NightElf] --> m76[Quest_LostMemories]
  m166[NebraKing] --> m81[Quest_KingOfSea]
  m104[McBurn] --> m102[Quest_ScorchedEarth]
  m104[McBurn] --> m167[Quest_TrialByFire]
  m104[McBurn] --> m41[ScorchedEarth]
  m168[GnollHunt] --> m152[PriestX]
  m150[Tentacles] --> m169[Ultros]
  m170[Cartographer] --> m126[Makenroh]
  m127[DragonHunt] --> m151[Montblanc]
  m171[Graves] --> m89[Npc]
  m37[Ziegfried] --> m47[Quest_DivineOrder]
  m37[Ziegfried] --> m66[Quest_ImperviousBeast]
  m136[Giott] --> m98[Loki]
  m136[Giott] --> m29[Mid]
  m136[Giott] --> m172[Watts]
  m18[Dwarves] --> m89[Npc]
  m18[Dwarves] --> m49[Quest_DwarfDisappearance]
  m50[Valigarmanda] --> m173[HauntedTree]
  m50[Valigarmanda] --> m37[Ziegfried]
  m98[Loki] --> m97[Quest_OreSupplies]
  m79[Monstrum] --> m78[Quest_Monstrum]
  m123[Frakir] --> m174[Quest_SpiritHunt]
  m175[Elysium] --> m176[Andre]
  m177[Kesha] --> m89[Npc]
  m122[Agrias] --> m63[Quest_HolyKnight]
  m20[Alma] --> m74[Quest_LightOfJudgment]
  m178[Anabel] --> m80[Quest_NebraAngler]
  m176[Andre] --> m175[Elysium]
  m40[BlazingDemon] --> m39[Quest_BlazingDemon]
  m83[BridgeBattle] --> m128[Gilgamesh]
  m83[BridgeBattle] --> m34[QuestCount]
  m43[Brothers] --> m51[Quest_EidolonChallenge]
  m43[Brothers] --> m179[Quest_Rematch]
  m24[Celeborn] --> m120[Quest_ZodiacAge]
  m180[Clemydar] --> m105[Quest_SeekDestroy]
  m158[CrystalBall] --> m88[Nimphrodel]
  m181[DarkEidolons] --> m182[Boss_Penance]
  m181[DarkEidolons] --> m183[DarkBahamut]
  m181[DarkEidolons] --> m184[DarkIfrit]
  m181[DarkEidolons] --> m185[DarkPhoenix]
  m184[DarkIfrit] --> m40[BlazingDemon]
  m184[DarkIfrit] --> m39[Quest_BlazingDemon]
  m185[DarkPhoenix] --> m40[BlazingDemon]
  m185[DarkPhoenix] --> m39[Quest_BlazingDemon]
  m112[Eden] --> m89[Npc]
  m112[Eden] --> m111[Quest_StrongestEidolon]
  m73[Exodus] --> m14[Boss_Exodus]
  m67[Fafnir] --> m66[Quest_ImperviousBeast]
  m67[Fafnir] --> m37[Ziegfried]
  m148[Famfrit] --> m15[Boss_Famfrit]
  m152[PriestX] --> m72[Quest_LastRites]
  m34[QuestCount] --> m160[LadyCurse]
  m34[QuestCount] --> m100[Quest_Phoenix]
  m34[QuestCount] --> m186[Shinra]
  m41[ScorchedEarth] --> m104[McBurn]
  m41[ScorchedEarth] --> m102[Quest_ScorchedEarth]
  m41[ScorchedEarth] --> m187[Quest_ScorchingTravel]
  m186[Shinra] --> m162[DimensionalBoundary]
  m90[ShinrasPlan] --> m96[AlmightyShinra]
  m68[Siegfried] --> m47[Quest_DivineOrder]
  m188[SpiritScroll] --> m189[VoiceOfForest]
  m190[Tonberry] --> m115[Quest_UltimaWeapon]
  m164[TropicalEssence] --> m25[DeathSeeker]
  m134[Turks] --> m137[AoMadoushi]
  m75[Ultima] --> m22[Boss_Ultima]
  m169[Ultros] --> m79[Monstrum]
  m169[Ultros] --> m150[Tentacles]
  m135[Valera] --> m116[Quest_WolfFangs]
  m110[Vodyan] --> m107[Quest_SpiritOfWater]
  m110[Vodyan] --> m109[Tiara]
  m189[VoiceOfForest] --> m7[Boss_Chaos]
  m172[Watts] --> m191[Quest_FieryWings]
